### ISSUE TITLE
Request for transfer: power-assert-js organization

### ISSUE THREAD

**Issue by twada** [power-assert-js/webpack-espower-loader#1]
Hi @zoncoen, I've created new organization [power-assert-js](https://github.com/power-assert-js) to help users to find related products easily, and I want you to transfer this project to power-assert-js org.

If you agree with me, please see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by zoncoen** [comment]
@twada I’m sorry for not replying sooner.

I agree with you. I'll transfer this repository to power-assert-js organization!

**Comment by twada** [comment]
@zoncoen Thanks a lot!!
